### ISSUE TITLE
Resize the fonts & Change the font for download button

### ISSUE THREAD

**Issue by Lolimipsu** [Takagi-VN-Dev/tkvn-site#21]
because of the recent change to a local font the main.css is a mess now, and the `<font size="15">` doesn't work with the local font for some reason so we need to change it

the 
`A fan visual novel game based on Soichirou Yamamoto's work.` is too thin so we either replace it with the Riffic bold font or use a more simplified and UI Font.

and the download button... we definitely need to replace the fonts.

![image](https://user-images.githubusercontent.com/44487404/106982288-c30f8500-679e-11eb-9256-533819b52497.png)

**Comment by hachiXhachi** [comment]
you can now change font size in my new commit, pls check it if you have time

**Comment by hachiXhachi** [comment]
regarding to the font style of the download button i turn it back to sans seriff cause i dont  know what font style to add xD
