### ISSUE TITLE
reworked website: Index-main button does not redirect to the download_page

### ISSUE THREAD

**Issue by Lolimipsu** [Takagi-VN-Dev/tkvn-site#31]
the index "Download now" button does not redirect to the download_page 
![image](https://user-images.githubusercontent.com/44487404/125240419-aca4c100-e31c-11eb-928a-2f86b0c79a96.png)

**Comment by Knamer95** [comment]
It should be fixed now :)

**Comment by Lolimipsu** [comment]
> It should be fixed now :)

thanks!
