### ISSUE TITLE
the index.html game logo doesn't show up when I use the bottom nav bar

### ISSUE THREAD

**Issue by Lolimipsu** [Takagi-VN-Dev/tkvn-site#8]
This issue keeps showing up before the bottom nav bar, the logo diesnt show up when i used the clickable ccbysa image

**Comment by Lolimipsu** [comment]
Sorry I wasn't clear of the objective, 

The objective is that to replace the old footer with the newer version, but it seems the game logo bugs out when the bottom screen is too big to show up

from this
![image](https://user-images.githubusercontent.com/44487404/102960373-c6b3b900-451c-11eb-96ad-f2f789d31ead.png)


To this
![image](https://user-images.githubusercontent.com/44487404/102960398-d7642f00-451c-11eb-9cab-77a8e2522218.png)

**Comment by hachiXhachi** [comment]
do you already code this one? if you did, can I have your code

**Comment by Lolimipsu** [comment]
fixed by @hachiXhachi
